version: '3'

services:

  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
    networks:
      - webnet
      
      
  celery:
    image: python-image:latest
    command: celery -A lensapp.app.celery worker --config=lensapp.config --concurrency=4
    user: nobody
    volumes:
      - '.:/lensapp'
    links:
      - rabbitmq
      - mongodb
    networks:
      - webnet

      
  monitor:
    image: python-image:latest
    ports:
     - "5555:5555"
    entrypoint: flower
    user: nobody
    command: -A lensapp.app.celery --port=5555
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - webnet


  application:
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    image: python-image:latest
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "lensapp.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/lensapp'
    ports:
      - '8000:8000'
    links:
      - mongodb
    networks:
      - webnet

      
  mongodb:
    image: mongo:3.3
    networks:
      - webnet

    
volumes:  
  # redis:
  rabbitmq:
  mongodb:
    

networks:
  webnet:
