version: '2'

services:
      

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6739:6739"

      
  celery:
    build: .
    command: celery -A lensapp.app.celery worker --loglevel=info --config=lensapp.config
    user: nobody
    volumes:
      - '.:/lensapp'
    links:
      - redis

      
  application:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "lensapp.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/lensapp'
    ports:
      - '8000:8000'

      
volumes:  
  redis:
