version: '3'

services:

  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
      
      
  celery:
    build: .
    command: celery -A lensapp.app.celery worker --config=lensapp.config --concurrency=4
    user: nobody
    volumes:
      - '.:/lensapp'
    links:
      - rabbitmq
      - mongodb

      
  monitor:
    build: .
    ports:
     - "5555:5555"
    entrypoint: flower
    user: nobody
    command: -A lensapp.app.celery --port=5555
    depends_on:
      - rabbitmq
      - mongodb


  application:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "lensapp.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/lensapp'
    ports:
      - '8000:8000'
    links:
      - mongodb

  mongodb:
    image: mongo:3.3

    
volumes:  
  # redis:
  rabbitmq:
  mongodb:
    
